# Generated by Django 4.2.16 on 2026-06-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrequisition",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
