# Generated by Django 4.2.16 on 2026-06-29 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_gl_auto_journal_reconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requisitions", "0002_add_rejection_reason_recall_interactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisitionapproval",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("fulfilled", "Fulfilled"),
                    ("dept_review", "Department Review"),
                    ("finance", "Finance Review"),
                    ("md_review", "MD Review"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="req_type",
            field=models.CharField(
                choices=[
                    ("fuel", "Fuel Requisition"),
                    ("materials", "Materials Requisition"),
                    ("repair_maintenance", "Repair & Maintenance"),
                    ("general_purchase", "General Purchase"),
                    ("store_item", "Store Item"),
                    ("external_purchase", "External Purchase"),
                    ("service", "Service Request"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("fulfilled", "Fulfilled"),
                    ("dept_review", "Department Review"),
                    ("finance", "Finance Review"),
                    ("md_review", "MD Review"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=255)),
                ("work_description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("payment_details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("logged", "Logged"),
                            ("pending_approval", "Pending Admin Approval"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="logged",
                        max_length=20,
                    ),
                ),
                ("admin_comments", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_schedules_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.expenseclaim",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_schedules_logged",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_schedule",
                        to="requisitions.staffrequisition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelPaymentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("finance_raised", "Payment Raised by Finance"),
                            ("md_paid", "MD Paid Directly (Record Update)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_ref", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.expenseclaim",
                    ),
                ),
                (
                    "requisition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_payment",
                        to="requisitions.staffrequisition",
                    ),
                ),
            ],
        ),
    ]
