# Generated by Django 4.2.16 on 2026-07-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0006_paid_status_and_payment_confirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrequisition",
            name="payment_send_money_phone",
            field=models.CharField(
                blank=True, help_text="M-Pesa Send Money phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="requisitionapproval",
            name="stage",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                    ("fulfilled", "Fulfilled"),
                    ("dept_review", "Department Review"),
                    ("finance", "Finance Review"),
                    ("md_review", "MD Review"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="payment_account_number",
            field=models.CharField(
                blank=True,
                help_text="M-Pesa Paybill account / bank account number",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="payment_business_number",
            field=models.CharField(
                blank=True, help_text="M-Pesa Paybill business number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mpesa_paybill", "M-Pesa Paybill"),
                    ("mpesa_till", "M-Pesa Till"),
                    ("mpesa_send_money", "M-Pesa Send Money"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffrequisition",
            name="payment_till_number",
            field=models.CharField(
                blank=True, help_text="M-Pesa Till number", max_length=50
            ),
        ),
    ]
