# Generated by Django 4.2.16 on 2026-06-29 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyorWeeklyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_no", models.CharField(max_length=20)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("weekly_activities", models.JSONField(default=list)),
                ("benchmark_summary", models.JSONField(default=list)),
                ("equipment_condition", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("next_week_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Surveyor Weekly Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurveyorDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("day", models.CharField(blank=True, max_length=20)),
                ("weather", models.CharField(blank=True, max_length=100)),
                ("surveyor_name", models.CharField(blank=True, max_length=100)),
                ("assistant", models.CharField(blank=True, max_length=100)),
                ("rtk_gps", models.CharField(blank=True, max_length=100)),
                ("total_station", models.CharField(blank=True, max_length=100)),
                ("auto_dumpy_level", models.CharField(blank=True, max_length=100)),
                ("staff_prism", models.CharField(blank=True, max_length=100)),
                ("vehicle_access", models.CharField(blank=True, max_length=100)),
                ("battery_calibration", models.CharField(blank=True, max_length=100)),
                ("survey_activities", models.JSONField(default=list)),
                ("control_points", models.JSONField(default=list)),
                ("issues", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("next_day_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Surveyor Daily Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MachineWeeklyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_no", models.CharField(max_length=20)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("machine_name", models.CharField(blank=True, max_length=100)),
                ("machine_id", models.CharField(blank=True, max_length=100)),
                ("machine_type", models.CharField(blank=True, max_length=100)),
                ("primary_operator", models.CharField(blank=True, max_length=100)),
                (
                    "opening_meter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "closing_meter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fuel_added",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_oil_added",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("hours_summary", models.JSONField(default=dict)),
                ("works_executed", models.JSONField(default=list)),
                ("maintenance_summary", models.JSONField(default=list)),
                ("breakdowns", models.JSONField(default=list)),
                ("materials", models.TextField(blank=True)),
                ("major_issues", models.TextField(blank=True)),
                ("safety_summary", models.TextField(blank=True)),
                ("next_week_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Weekly Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MachineDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("day", models.CharField(blank=True, max_length=20)),
                ("weather", models.CharField(blank=True, max_length=100)),
                ("machine_name", models.CharField(blank=True, max_length=100)),
                ("machine_id", models.CharField(blank=True, max_length=100)),
                ("machine_type", models.CharField(blank=True, max_length=100)),
                ("operator_name", models.CharField(blank=True, max_length=100)),
                ("fuel_type", models.CharField(blank=True, max_length=50)),
                ("operator_licence", models.CharField(blank=True, max_length=100)),
                ("start_time", models.CharField(blank=True, max_length=10)),
                ("end_time", models.CharField(blank=True, max_length=10)),
                (
                    "hrs_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "hrs_idle_breakdown",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_hrs_on_site",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "opening_meter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "closing_meter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fuel_added",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "oil_fluids_added",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fuel_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("work_activities", models.JSONField(default=list)),
                ("maintenance_checks", models.JSONField(default=list)),
                ("breakdowns", models.JSONField(default=list)),
                ("instructions", models.TextField(blank=True)),
                ("delays", models.TextField(blank=True)),
                ("safety_remarks", models.TextField(blank=True)),
                ("next_day_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Daily Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForemanWeeklyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_no", models.CharField(max_length=20)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("labour_summary", models.JSONField(default=dict)),
                ("works_executed", models.JSONField(default=list)),
                ("materials", models.TextField(blank=True)),
                ("major_issues", models.TextField(blank=True)),
                ("safety_summary", models.TextField(blank=True)),
                ("next_week_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foreman Weekly Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ForemanDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("contract_no", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("day", models.CharField(blank=True, max_length=20)),
                ("weather", models.CharField(blank=True, max_length=100)),
                ("skilled_labour", models.IntegerField(default=0)),
                ("semi_skilled", models.IntegerField(default=0)),
                ("unskilled", models.IntegerField(default=0)),
                ("operators", models.IntegerField(default=0)),
                ("supervisors", models.IntegerField(default=0)),
                ("visitors", models.IntegerField(default=0)),
                ("total_workforce", models.IntegerField(default=0)),
                ("shift_hours", models.CharField(blank=True, max_length=50)),
                ("plant_equipment", models.JSONField(default=list)),
                ("work_activities", models.JSONField(default=list)),
                ("instructions", models.TextField(blank=True)),
                ("delays", models.TextField(blank=True)),
                ("safety_remarks", models.TextField(blank=True)),
                ("next_day_plan", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foreman Daily Report",
                "ordering": ["-submitted_at"],
                "abstract": False,
            },
        ),
    ]
