# Generated by Django 4.2.16 on 2026-07-09 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("date", models.DateField()),
                (
                    "image",
                    models.ImageField(upload_to=reports.models.site_photo_upload_path),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("progress", "Work Progress"),
                            ("issue", "Issue / Problem"),
                            ("safety", "Safety"),
                            ("material", "Material Delivery"),
                            ("equipment", "Equipment"),
                            ("completion", "Completion"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "location_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "report_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("report_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
