# Generated by Django 4.2.16 on 2026-06-30 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0010_gl_auto_journal_reconciliation"),
        ("fleet", "0007_vehicle_source_is_live"),
        ("notifications", "0002_scheduled_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRenewalCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_name", models.CharField(max_length=200)),
                ("asset_ref", models.CharField(blank=True, max_length=100)),
                ("compliance_type", models.CharField(max_length=30)),
                ("original_expiry", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="open", max_length=30)),
                ("provider_name", models.CharField(blank=True, max_length=200)),
                ("provider_contact", models.CharField(blank=True, max_length=200)),
                ("contacted_date", models.DateField(blank=True, null=True)),
                ("invoice_ref", models.CharField(blank=True, max_length=100)),
                (
                    "invoice_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("invoice_due_date", models.DateField(blank=True, null=True)),
                ("new_expiry", models.DateField(blank=True, null=True)),
                ("new_cert_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_cases",
                        to="finance.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_compliance_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle_compliance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewal_cases",
                        to="fleet.vehiclecompliance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCaseStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step", models.CharField(max_length=30)),
                ("note", models.TextField(blank=True)),
                ("actioned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="notifications.compliancerenewalcase",
                    ),
                ),
            ],
            options={
                "ordering": ["actioned_at"],
            },
        ),
    ]
