# Generated by Django 4.2.16 on 2026-07-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_device_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("pr_approved", "PR Approved"),
                    ("pr_rejected", "PR Rejected"),
                    ("pr_submitted", "PR Submitted for Approval"),
                    ("po_approved", "PO Approved"),
                    ("low_stock", "Low Stock Alert"),
                    ("tender_due", "Tender Deadline Soon"),
                    ("ipc_issued", "IPC Issued"),
                    ("compliance_expiry", "Compliance Expired"),
                    ("compliance_warning", "Compliance Expiring Soon"),
                    ("expense_submitted", "Expense Claim Submitted"),
                    ("expense_approved", "Expense Claim Approved"),
                    ("expense_rejected", "Expense Claim Rejected"),
                    ("req_submitted", "Requisition Submitted"),
                    ("req_approved", "Requisition Approved"),
                    ("req_rejected", "Requisition Rejected"),
                    ("req_dept_review", "Requisition Sent to MD"),
                    ("req_fulfilled", "Requisition Fulfilled"),
                    ("sr_submitted", "Store Request Submitted"),
                    ("sr_approved", "Store Request Approved"),
                    ("sr_rejected", "Store Request Rejected"),
                    ("sr_dispatched", "Store Request Dispatched"),
                    ("sr_received", "Store Request Received"),
                    ("sr_returned", "Store Request Returned"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
