# Generated by Django 4.2.16 on 2026-07-09 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("inspection_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("earthworks", "Earthworks"),
                            ("concrete", "Concrete"),
                            ("structural", "Structural"),
                            ("finishing", "Finishing"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("road", "Road Works"),
                            ("drainage", "Drainage"),
                            ("general", "General"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("activity_description", models.CharField(max_length=300)),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("inspector_name", models.CharField(max_length=200)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("conditional", "Conditional Pass"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("checklist_items", models.JSONField(default=list)),
                ("observations", models.TextField(blank=True, default="")),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("re_inspection_date", models.DateField(blank=True, null=True)),
                (
                    "re_inspection_result",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "approved_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PunchListItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "item_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="punch_list_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="NCR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("ncr_number", models.CharField(blank=True, default="", max_length=50)),
                ("date_raised", models.DateField()),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                        ],
                        default="minor",
                        max_length=10,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, default="")),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("action_due", models.DateField(blank=True, null=True)),
                ("action_completed", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("closed", "Closed"),
                            ("voided", "Voided"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("raised_by", models.CharField(blank=True, default="", max_length=200)),
                ("closed_by", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs",
                        to="quality.qualityinspection",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_raised", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("concrete_cube", "Concrete Cube Test"),
                            ("compaction", "Compaction Test"),
                            ("soil_cbr", "Soil CBR"),
                            ("aggregate", "Aggregate Test"),
                            ("asphalt", "Asphalt Test"),
                            ("water", "Water Quality"),
                            ("steel", "Steel Test"),
                            ("other", "Other"),
                        ],
                        default="concrete_cube",
                        max_length=20,
                    ),
                ),
                ("sample_id", models.CharField(blank=True, default="", max_length=100)),
                ("test_date", models.DateField()),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("tested_by", models.CharField(blank=True, default="", max_length=200)),
                ("lab_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "value_obtained",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "required_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date", "-created_at"],
            },
        ),
    ]
