# Generated by Django 4.2.16 on 2026-06-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("contract_number", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("contract_sum", models.DecimalField(decimal_places=2, max_digits=18)),
                ("project_location", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tendering", "Tendering"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("completed", "Completed"),
                        ],
                        default="tendering",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "project_manager"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tender_number", models.CharField(max_length=100, unique=True)),
                ("tender_description", models.TextField()),
                ("tender_value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tender_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("awarded", "Awarded"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("award_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenders",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="project_documents/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BOQItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("unit", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_rate", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=18
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Physical completion percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "boq_version",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("revised", "Revised"),
                            ("variation_order", "Variation Order"),
                        ],
                        default="original",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="projects.boqitem",
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boq_items",
                        to="projects.tender",
                    ),
                ),
            ],
            options={
                "ordering": ["item_code"],
            },
        ),
    ]
