import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('client', models.CharField(blank=True, max_length=300)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning','Planning'),('active','Active'),('on_hold','On Hold'),('completed','Completed'),('suspended','Suspended')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('vop_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to='projects.project')),
            ],
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.CreateModel(
            name='BOQBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='projects.boq')),
            ],
            options={'ordering': ['order', 'bill_number']},
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.boqbill')),
            ],
            options={'ordering': ['item_number']},
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('period_weeks', models.PositiveIntegerField(default=8)),
                ('status', models.CharField(choices=[('draft','Draft'),('approved','Approved'),('locked','Locked')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='BudgetRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('used_in', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='projects.budget')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_no', models.PositiveIntegerField(blank=True, null=True)),
                ('month_no', models.PositiveIntegerField(blank=True, null=True)),
                ('work_focus', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('materials','Materials'),('fuel','Fuel/Plant'),('labour','Labour/HR'),('casuals','Casuals'),('management','Management Reserve'),('other','Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('waste_allowance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('high_variance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('low_case_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('high_case_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.budget')),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='projects.boqitem')),
            ],
            options={'ordering': ['week_no', 'month_no', 'category']},
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipc_number', models.PositiveIntegerField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('chainage_from', models.CharField(blank=True, max_length=20)),
                ('chainage_to', models.CharField(blank=True, max_length=20)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_certified', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft','Draft'),('submitted','Submitted'),('certified','Certified'),('paid','Paid'),('disputed','Disputed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipcs', to='projects.project')),
            ],
            options={'ordering': ['project', 'ipc_number'], 'unique_together': {('project', 'ipc_number')}},
        ),
        migrations.CreateModel(
            name='IPCItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity_this_ipc', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('quantity_to_date', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ipc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.ipc')),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipc_items', to='projects.boqitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_description', models.TextField()),
                ('expected_impact', models.TextField(blank=True)),
                ('budget_treatment', models.TextField(blank=True)),
                ('realistic_range', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('impact_level', models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open','Open'),('mitigated','Mitigated'),('closed','Closed'),('escalated','Escalated')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('site_engineer','Site Engineer'),('general_foreman','General Foreman'),('surveyor','Surveyor'),('foreman','Foreman'),('hse_lead','HSE Lead'),('clerk','Clerk'),('operator','Operator'),('casual','Casual'),('other','Other')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('include_in_budget', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_no', models.PositiveIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('work_focus', models.TextField(blank=True)),
                ('materials_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fuel_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('casuals_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('casual_headcount', models.PositiveIntegerField(default=0)),
                ('casual_person_days', models.PositiveIntegerField(default=0)),
                ('progress_notes', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('next_week_plan', models.TextField(blank=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='projects.project')),
            ],
            options={'ordering': ['project', 'week_no'], 'unique_together': {('project', 'week_no')}},
        ),
    ]
