# Generated by Django 4.2.16 on 2026-06-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_boqitem_actual_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boq",
            options={},
        ),
        migrations.AlterModelOptions(
            name="budget",
            options={},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="budget",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ipc",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="boq",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="budget",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("locked", "Locked"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="budgetlineitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("materials", "Materials"),
                    ("fuel", "Fuel"),
                    ("labour", "Labour"),
                    ("casuals", "Casuals"),
                    ("management", "Management"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budgetrate",
            name="used_in",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="budgetrate",
            name="value",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="ipc",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ipcs",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="ipc",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("certified", "Certified"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                    ("disputed", "Disputed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
