# Generated by Django 4.2.16 on 2026-06-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent Transfer"),
                            ("temporary", "Temporary Transfer"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("site", "Site / Field"),
                            ("head_office", "Head Office"),
                            ("branch", "Branch Office"),
                        ],
                        max_length=15,
                    ),
                ),
                ("from_location", models.CharField(max_length=200)),
                ("to_location", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for permanent transfers",
                        null=True,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "relocation_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-off relocation payment",
                        max_digits=12,
                    ),
                ),
                (
                    "daily_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Daily allowance rate",
                        max_digits=10,
                    ),
                ),
                (
                    "daily_allowance_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days for daily allowance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="hr.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
