# Generated by Django 4.2.16 on 2026-06-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("hr", "0002_employeetransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetransfer",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to project site (for site transfers)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_transfers",
                to="projects.project",
            ),
        ),
    ]
