# Generated by Django 4.2.16 on 2026-06-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("hr", "0003_employeetransfer_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollentry",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this salary is charged to. Leave blank for HQ/overhead staff.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_entries",
                to="projects.project",
            ),
        ),
    ]
