# Generated by Django 4.2.16 on 2026-06-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_payrollentry_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("contract", "Employment Contract"),
                    ("id_copy", "ID Copy"),
                    ("certificate", "Certificate"),
                    ("nssf_card", "NSSF Card"),
                    ("nhif_card", "SHA/SHIF Card"),
                    ("kra_cert", "KRA Certificate"),
                    ("medical", "Medical Certificate"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
