# Generated by Django 4.2.16 on 2026-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_fleet_register_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="account_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employee",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="chronic_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="disability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("visual", "Visual"),
                    ("hearing", "Hearing"),
                    ("physical", "Physical"),
                    ("other", "Other"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="disability_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact2_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact2_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact2_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_insurance_category",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="employee",
            name="medical_insurance_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_alt_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="next_of_kin_relation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("contract", "Employment Contract"),
                    ("id_copy", "National ID Copy"),
                    ("certificate", "Certificate"),
                    ("nssf_card", "NSSF Card"),
                    ("nhif_card", "SHA/SHIF Card"),
                    ("kra_cert", "KRA Certificate"),
                    ("medical", "Medical Certificate"),
                    ("cv", "CV / Resume"),
                    ("good_conduct", "Certificate of Good Conduct"),
                    ("academics", "Academic Certificates"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
