# Generated by Django 4.2.16 on 2026-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_employee_account_name_employee_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="medical_declaration",
            field=models.TextField(blank=True),
        ),
    ]
