# Generated by Django 4.2.16 on 2026-06-27 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0007_employee_medical_declaration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Casual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        db_index=True,
                        help_text="National ID — used to identify returning casuals",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name as it appears on ID", max_length=200
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Phone for mobile money payment", max_length=20
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        help_text="Head Office or project site location", max_length=200
                    ),
                ),
                (
                    "assignment",
                    models.TextField(help_text="Work assigned to the casual"),
                ),
                (
                    "daily_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("foreman_approved", "Foreman Approved"),
                            ("hr_approved", "HR Approved"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("foreman_approved_at", models.DateTimeField(blank=True, null=True)),
                ("hr_approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casuals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foreman_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casuals_foreman_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hr_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casuals_hr_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CasualDailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "days_worked",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="1 = full day, 0.5 = half day",
                        max_digits=4,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "casual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="hr.casual",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casual_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_date"],
                "unique_together": {("casual", "work_date")},
            },
        ),
    ]
