# Generated by Django 4.2.16 on 2026-07-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_employee_reports_to_work_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="casual",
            name="activated_date",
            field=models.DateField(
                blank=True,
                help_text="Date the casual was last activated for work",
                null=True,
            ),
        ),
    ]
