# Generated by Django 4.2.16 on 2026-07-10 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_gl_auto_journal_reconciliation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0011_casual_activated_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CasualDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=30, unique=True)),
                ("report_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casual_reports_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_claim",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casual_report",
                        to="finance.expenseclaim",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casual_reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CasualDailyReportItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("id_number", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("assignment", models.TextField()),
                ("placement", models.CharField(max_length=200)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "days_worked",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "casual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_items",
                        to="hr.casual",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hr.casualdailyreport",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "casual")},
            },
        ),
    ]
