# Generated by Django 4.2.16 on 2026-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_casual_daily_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetransfer",
            name="allowance_eligible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this employee is entitled to movement allowances",
            ),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="lunch_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days eligible for lunch allowance (KES 500/day)"
            ),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="overnight_nights",
            field=models.PositiveIntegerField(
                default=0, help_text="Nights requiring accommodation (KES 1,500/night)"
            ),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="staff_category",
            field=models.CharField(
                choices=[
                    ("subordinate", "Subordinate Staff"),
                    ("management", "Management Staff"),
                ],
                default="subordinate",
                help_text="Determines relocation allowance tier",
                max_length=15,
            ),
        ),
    ]
