# Generated by Django 4.2.16 on 2026-07-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_transfer_transport_allowances"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[("probation", "On Probation"), ("confirmed", "Confirmed")],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="licence_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="licence_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
