# Generated by Django 4.2.16 on 2026-06-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("vehicle_wise", "Vehicle Wise"),
                            ("token_based", "Token Based"),
                        ],
                        default="token_based",
                        max_length=20,
                    ),
                ),
                ("base_url", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("project_id", models.IntegerField(default=37)),
                ("is_active", models.BooleanField(default=True)),
                ("cached_token", models.TextField(blank=True)),
                ("token_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fleet API Config",
                "verbose_name_plural": "Fleet API Configs",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vehicle_no", models.CharField(max_length=50, unique=True)),
                ("vehicle_name", models.CharField(blank=True, max_length=200)),
                ("imei", models.CharField(blank=True, max_length=50)),
                ("vehicle_type", models.CharField(blank=True, max_length=50)),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("petrol", "Petrol"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="diesel",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_capacity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("last_status", models.CharField(blank=True, max_length=20)),
                ("last_location", models.TextField(blank=True)),
                (
                    "last_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "last_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "last_speed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "last_fuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("last_odometer", models.BigIntegerField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="fleet.fleetapiconfig",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle_no"],
            },
        ),
        migrations.CreateModel(
            name="TripRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("start_location", models.TextField(blank=True)),
                ("end_location", models.TextField(blank=True)),
                (
                    "start_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "start_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "end_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "end_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("start_odometer", models.BigIntegerField(default=0)),
                ("end_odometer", models.BigIntegerField(default=0)),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                (
                    "max_speed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fuel_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("driver_name", models.CharField(blank=True, max_length=200)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("service", "Routine Service"),
                            ("repair", "Repair"),
                            ("inspection", "Inspection"),
                            ("tyre", "Tyre Change"),
                            ("oil", "Oil Change"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("odometer_at_service", models.BigIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("next_service_date", models.DateField(blank=True, null=True)),
                (
                    "next_service_odometer",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FuelEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("fill", "Fuel Fill"),
                            ("drain", "Fuel Drain"),
                            ("theft", "Possible Theft"),
                        ],
                        max_length=10,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("location_name", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("fuel_before", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fuel_after", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fuel_change", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_events",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="FleetAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("sos", "SOS Emergency"),
                            ("speeding", "Overspeeding"),
                            ("low_fuel", "Low Fuel"),
                            ("fuel_drain", "Fuel Drain/Theft"),
                            ("ignition_off_moving", "Moving Without Ignition"),
                            ("idle_long", "Long Idle"),
                            ("device_offline", "Device Offline"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleLiveData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("device_datetime", models.DateTimeField(blank=True, null=True)),
                ("gps_actual_time", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_name", models.TextField(blank=True)),
                ("angle", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=20)),
                (
                    "speed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("gps_on", models.BooleanField(default=False)),
                ("ignition_on", models.BooleanField(default=False)),
                ("power_on", models.BooleanField(default=False)),
                ("immobilize_state", models.CharField(blank=True, max_length=20)),
                (
                    "fuel_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("battery_percentage", models.IntegerField(blank=True, null=True)),
                (
                    "external_volt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("odometer", models.BigIntegerField(default=0)),
                ("sos", models.BooleanField(default=False)),
                ("driver_name", models.CharField(blank=True, max_length=200)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_data",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "index_together": {("vehicle", "fetched_at")},
            },
        ),
    ]
