# Generated by Django 4.2.16 on 2026-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fuel_sensor_unit",
            field=models.CharField(blank=True, default="%", max_length=10),
        ),
    ]
