# Generated by Django 4.2.16 on 2026-06-22 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_fleet_register_fields"),
        ("fleet", "0002_fuel_sensor_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="asset_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="asset_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="asset_sub_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_site",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="erp_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="erp_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OPER", "Operational"),
                    ("NON-OPER", "Non-Operational"),
                    ("IDLE", "Idle"),
                    ("UNKNOWN", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="known_defects",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="meter_reading",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="priority_flag",
            field=models.CharField(
                blank=True,
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="required_actions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year_acquired",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year_manufacture",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fleetalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("sos", "SOS Emergency"),
                    ("speeding", "Overspeeding"),
                    ("low_fuel", "Low Fuel"),
                    ("fuel_drain", "Fuel Drain/Theft"),
                    ("ignition_off_moving", "Moving Without Ignition"),
                    ("idle_long", "Long Idle"),
                    ("device_offline", "Device Offline"),
                    ("insurance_expiry", "Insurance Expiring/Expired"),
                    ("inspection_expiry", "Inspection Cert Expiring/Expired"),
                    ("speed_governor_expiry", "Speed Governor Cert Expiring/Expired"),
                    ("compliance_issue", "Compliance Issue"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="VehicleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=200)),
                ("site", models.CharField(blank=True, max_length=200)),
                ("is_current", models.BooleanField(default=True)),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance"),
                            ("inspection", "Inspection Certificate"),
                            ("speed_governor", "Speed Governor Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("not_in_system", "Not in System"),
                            ("not_applicable", "N/A"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["compliance_type"],
                "unique_together": {("vehicle", "compliance_type")},
            },
        ),
    ]
