# Generated by Django 4.2.16 on 2026-06-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_live_fuel_unit_alert_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('geofence_type', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', max_length=10)),
                ('coordinates', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fuelevent',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fuelevent',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fleetalert',
            name='alert_type',
            field=models.CharField(choices=[('sos', 'SOS Emergency'), ('speeding', 'Overspeeding'), ('low_fuel', 'Low Fuel'), ('fuel_fill', 'Fuel Refill'), ('fuel_drain', 'Fuel Drain/Theft'), ('ignition_off_moving', 'Moving Without Ignition'), ('idle_long', 'Long Idle'), ('device_offline', 'Device Offline'), ('insurance_expiry', 'Insurance Expiring/Expired'), ('inspection_expiry', 'Inspection Cert Expiring/Expired'), ('speed_governor_expiry', 'Speed Governor Cert Expiring/Expired'), ('compliance_issue', 'Compliance Issue'), ('service_due', 'Service / Maintenance Due'), ('maintenance_due', 'Maintenance Due'), ('geofence', 'Geofence Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='fuel_after',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='fuel_before',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuelevent',
            name='fuel_change',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_fuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelivedata',
            name='fuel_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.geofence')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('kerosene', 'Kerosene')], max_length=20)),
                ('location', models.CharField(default='Nairobi', max_length=100)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', 'location', 'fuel_type'],
                'unique_together': {('fuel_type', 'location', 'effective_date')},
            },
        ),
    ]
