# Generated by Django 4.2.16 on 2026-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0009_keyissuance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyissuance",
            name="return_body_condition",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_brakes",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_engine_oil",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_fuel_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Full"),
                    ("three_quarter", "3/4"),
                    ("half", "1/2"),
                    ("quarter", "1/4"),
                    ("empty", "Empty"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_lights",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_tire_condition",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="keyissuance",
            name="return_wipers",
            field=models.CharField(
                blank=True,
                choices=[("ok", "OK"), ("not_ok", "Not OK"), ("na", "N/A")],
                default="",
                max_length=10,
            ),
        ),
    ]
