# Generated by Django 4.2.16 on 2026-07-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0010_alter_keyissuance_return_body_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyissuance",
            name="status",
            field=models.CharField(
                choices=[
                    ("out", "Out"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                    ("dispatched_to_site", "Dispatched to Site"),
                ],
                default="out",
                max_length=20,
            ),
        ),
    ]
