# Generated by Django 4.2.16 on 2026-06-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("kra_pin", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="TenderOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opportunity_name", models.CharField(max_length=255)),
                ("tender_number", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("qualified", "Qualified"),
                            ("bid_prep", "Bid Preparation"),
                            ("submitted", "Submitted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                ("submission_deadline", models.DateTimeField(blank=True, null=True)),
                ("probability_percent", models.IntegerField(blank=True, null=True)),
                ("win_loss_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="crm.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tender opportunities",
                "ordering": ["-created_at"],
            },
        ),
    ]
