from django.urls import path
from .views import (
    AccountListCreateView, AccountDetailView,
    InvoiceListCreateView, InvoiceDetailView,
    BillListCreateView, BillDetailView,
    PaymentListCreateView,
    BankTransactionListCreateView, CreditNoteListCreateView,
    ExpenseClaimListCreateView, ExpenseClaimDetailView,
    ExpenseClaimSubmitView, ExpenseClaimReviewView,
    CashFlowView, ContractProfitabilityView,
    RetentionScheduleView, RetentionReleaseListCreateView,
    RetentionReleaseDetailView, RetentionMarkReleasedView,
    AgedDebtorsView, AgedCreditorsView,
    FinanceDashboardView,
    ProjectBudgetListCreateView, ProjectBudgetDetailView, BudgetVsActualView,
    VATSummaryView, WHTRegisterView,
    PaymentCertificateListCreateView, PaymentCertificateDetailView,
    PerformanceBondListCreateView, PerformanceBondDetailView,
    TimesheetListCreateView, TimesheetDetailView, TimesheetSubmitView, TimesheetReviewView,
    PayrollSummaryView,
    JournalEntryListCreateView, JournalEntryDetailView,
    JournalPostView, JournalReverseView, TrialBalanceView,
    JournalApproveView, JournalRejectView, JournalSubmitForApprovalView,
    InvoiceReconcileView, BillReconcileView,
    BankReconciliationListCreateView, BankReconciliationDetailView, BankReconciliationCloseView,
    QBConfigView, QBConnectView, QBCallbackView, QBDisconnectView, QBSyncView, QBSyncLogListView,
    BalanceSheetView, IncomeStatementView,
)

urlpatterns = [
    path('dashboard/',                            FinanceDashboardView.as_view(),              name='finance-dashboard'),
    path('accounts/',                             AccountListCreateView.as_view(),             name='account-list'),
    path('accounts/<uuid:pk>/',                   AccountDetailView.as_view(),                 name='account-detail'),
    path('invoices/',                             InvoiceListCreateView.as_view(),             name='invoice-list'),
    path('invoices/<uuid:pk>/',                   InvoiceDetailView.as_view(),                 name='invoice-detail'),
    path('bills/',                                BillListCreateView.as_view(),                name='bill-list'),
    path('bills/<uuid:pk>/',                      BillDetailView.as_view(),                    name='bill-detail'),
    path('payments/',                             PaymentListCreateView.as_view(),             name='payment-list'),
    path('bank-transactions/',                    BankTransactionListCreateView.as_view(),     name='bank-transaction-list'),
    path('credit-notes/',                         CreditNoteListCreateView.as_view(),          name='credit-note-list'),
    path('expenses/',                             ExpenseClaimListCreateView.as_view(),        name='expense-list'),
    path('expenses/<uuid:pk>/',                   ExpenseClaimDetailView.as_view(),            name='expense-detail'),
    path('expenses/<uuid:pk>/submit/',            ExpenseClaimSubmitView.as_view(),            name='expense-submit'),
    path('expenses/<uuid:pk>/review/',            ExpenseClaimReviewView.as_view(),            name='expense-review'),
    path('cash-flow/',                            CashFlowView.as_view(),                     name='cash-flow'),
    path('profitability/',                        ContractProfitabilityView.as_view(),         name='profitability'),
    path('retention/',                            RetentionScheduleView.as_view(),             name='retention-schedule'),
    path('retention/releases/',                   RetentionReleaseListCreateView.as_view(),    name='retention-release-list'),
    path('retention/releases/<uuid:pk>/',         RetentionReleaseDetailView.as_view(),        name='retention-release-detail'),
    path('retention/releases/<uuid:pk>/action/',  RetentionMarkReleasedView.as_view(),         name='retention-release-action'),
    path('aged-debtors/',                         AgedDebtorsView.as_view(),                  name='aged-debtors'),
    path('aged-creditors/',                       AgedCreditorsView.as_view(),                name='aged-creditors'),
    # Budget vs Actual
    path('budgets/',                              ProjectBudgetListCreateView.as_view(),       name='budget-list'),
    path('budgets/<uuid:pk>/',                    ProjectBudgetDetailView.as_view(),           name='budget-detail'),
    path('budget-vs-actual/',                     BudgetVsActualView.as_view(),               name='budget-vs-actual'),
    # Tax & Compliance
    path('vat-summary/',                          VATSummaryView.as_view(),                   name='vat-summary'),
    path('wht-register/',                         WHTRegisterView.as_view(),                  name='wht-register'),
    # Payment Certificates
    path('certificates/',                         PaymentCertificateListCreateView.as_view(), name='certificate-list'),
    path('certificates/<uuid:pk>/',               PaymentCertificateDetailView.as_view(),     name='certificate-detail'),
    # Performance Bonds
    path('bonds/',                                PerformanceBondListCreateView.as_view(),    name='bond-list'),
    path('bonds/<uuid:pk>/',                      PerformanceBondDetailView.as_view(),        name='bond-detail'),
    # Payroll / Timesheets
    path('timesheets/',                           TimesheetListCreateView.as_view(),          name='timesheet-list'),
    path('timesheets/<uuid:pk>/',                 TimesheetDetailView.as_view(),              name='timesheet-detail'),
    path('timesheets/<uuid:pk>/submit/',          TimesheetSubmitView.as_view(),              name='timesheet-submit'),
    path('timesheets/<uuid:pk>/review/',          TimesheetReviewView.as_view(),              name='timesheet-review'),
    path('payroll-summary/',                      PayrollSummaryView.as_view(),               name='payroll-summary'),
    # Invoice / Bill reconciliation
    path('invoices/<uuid:pk>/reconcile/',         InvoiceReconcileView.as_view(),             name='invoice-reconcile'),
    path('bills/<uuid:pk>/reconcile/',            BillReconcileView.as_view(),                name='bill-reconcile'),
    # Bank reconciliation
    path('bank-reconciliations/',                 BankReconciliationListCreateView.as_view(), name='bank-reconciliation-list'),
    path('bank-reconciliations/<uuid:pk>/',       BankReconciliationDetailView.as_view(),     name='bank-reconciliation-detail'),
    path('bank-reconciliations/<uuid:pk>/close/', BankReconciliationCloseView.as_view(),      name='bank-reconciliation-close'),
    # GL Journal
    path('journals/',                             JournalEntryListCreateView.as_view(),       name='journal-list'),
    path('journals/<uuid:pk>/',                   JournalEntryDetailView.as_view(),           name='journal-detail'),
    path('journals/<uuid:pk>/submit/',            JournalSubmitForApprovalView.as_view(),     name='journal-submit'),
    path('journals/<uuid:pk>/approve/',           JournalApproveView.as_view(),               name='journal-approve'),
    path('journals/<uuid:pk>/reject/',            JournalRejectView.as_view(),                name='journal-reject'),
    path('journals/<uuid:pk>/post/',              JournalPostView.as_view(),                  name='journal-post'),
    path('journals/<uuid:pk>/reverse/',           JournalReverseView.as_view(),               name='journal-reverse'),
    path('trial-balance/',                        TrialBalanceView.as_view(),                 name='trial-balance'),
    # Financial Statements
    path('balance-sheet/',      BalanceSheetView.as_view(),    name='balance-sheet'),
    path('income-statement/',   IncomeStatementView.as_view(), name='income-statement'),
    # QuickBooks integration
    path('quickbooks/config/',      QBConfigView.as_view(),      name='qb-config'),
    path('quickbooks/connect/',     QBConnectView.as_view(),      name='qb-connect'),
    path('quickbooks/callback/',    QBCallbackView.as_view(),     name='qb-callback'),
    path('quickbooks/disconnect/',  QBDisconnectView.as_view(),   name='qb-disconnect'),
    path('quickbooks/sync/',        QBSyncView.as_view(),         name='qb-sync'),
    path('quickbooks/logs/',        QBSyncLogListView.as_view(),  name='qb-logs'),
]
