# Generated by Django 4.2.16 on 2026-06-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("finance", "0004_budget_certificates_bonds"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Journal"),
                            ("invoice", "Invoice (AR)"),
                            ("payment", "Payment Receipt"),
                            ("bill", "Supplier Bill (AP)"),
                            ("expense", "Expense Claim"),
                            ("payroll", "Payroll Allocation"),
                            ("adjustment", "Adjustment"),
                            ("period_close", "Period-End Close"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("entry_date", models.DateField()),
                ("period", models.CharField(blank=True, max_length=7)),
                ("description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("is_reversing", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversal",
                        to="finance.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                ("week_start", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheets_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_date", models.DateField()),
                (
                    "cost_code",
                    models.CharField(
                        choices=[
                            ("materials", "Materials"),
                            ("labour", "Labour"),
                            ("plant", "Plant & Equipment"),
                            ("subcontractor", "Subcontractor"),
                            ("preliminaries", "Preliminaries"),
                            ("overhead", "Overhead"),
                            ("other", "Other"),
                        ],
                        default="labour",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.timesheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cost_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("materials", "Materials"),
                            ("labour", "Labour"),
                            ("plant", "Plant & Equipment"),
                            ("subcontractor", "Subcontractor"),
                            ("preliminaries", "Preliminaries"),
                            ("overhead", "Overhead"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="finance.account",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
