# Generated by Django 4.2.16 on 2026-06-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("construction_materials", "Construction Materials"),
                            ("spare_parts", "Spare Parts"),
                            ("fuel", "Fuel & Lubricants"),
                            ("ppe_safety", "PPE & Safety"),
                            ("office_consumables", "Office Consumables"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "valuation_method",
                    models.CharField(
                        choices=[("fifo", "FIFO"), ("wac", "Weighted Average Cost")],
                        default="wac",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["item_code"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "storekeeper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("grn", "Goods Received Note"),
                            ("issue", "Stock Issue"),
                            ("transfer", "Store Transfer"),
                            ("return", "Return to Store"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                ("transaction_date", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "boq_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.boqitem",
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_transfers",
                        to="inventory.store",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grns",
                        to="procurement.purchaseorder",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to="projects.project",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "weighted_avg_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "store")},
            },
        ),
    ]
