# Generated by Django 4.2.16 on 2026-06-30 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_asset_transport_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="issued_to",
            field=models.ForeignKey(
                blank=True,
                help_text="System user who received the issued item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_stock_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="issued_to_name",
            field=models.CharField(
                blank=True,
                help_text="Name of recipient if not a system user",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="inspection_cert_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "Valid"),
                    ("expired", "Expired"),
                    ("not_in_system", "Not in System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="insurance_policy_type",
            field=models.CharField(
                blank=True, help_text="e.g. Comprehensive, Third Party", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="speed_governor_cert_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "Valid"),
                    ("expired", "Expired"),
                    ("not_in_system", "Not in System"),
                ],
                max_length=20,
            ),
        ),
    ]
