# Generated by Django 4.2.16 on 2026-07-03 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0006_add_issued_to_stock_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_stock_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("construction_materials", "Construction Materials"),
                    ("spare_parts", "Spare Parts"),
                    ("fuel", "Fuel & Lubricants"),
                    ("ppe_safety", "PPE & Safety"),
                    ("office_consumables", "Office Consumables"),
                    ("stationery", "Stationery"),
                    ("cleaning", "Cleaning Supplies"),
                    ("kitchen", "Kitchen / Canteen"),
                    ("electronics", "Electronics"),
                    ("tools", "Tools & Equipment"),
                    ("uniforms", "Uniforms & Clothing"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
