# Generated by Django 4.2.16 on 2026-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_deactivate_legacy_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("construction_materials", "Construction Materials"),
                    ("road_materials", "Road Materials"),
                    ("spare_parts", "Spare Parts"),
                    ("vehicle_parts", "Vehicle Spare Parts"),
                    ("fuel", "Fuel & Lubricants"),
                    ("ppe_safety", "PPE & Safety"),
                    ("office_consumables", "Office Consumables"),
                    ("stationery", "Stationery"),
                    ("furniture", "Furniture & Fittings"),
                    ("cleaning", "Cleaning Supplies"),
                    ("kitchen", "Kitchen / Canteen"),
                    ("food_ingredients", "Food & Ingredients"),
                    ("electronics", "Electronics"),
                    ("networking", "Networking Equipment"),
                    ("software_license", "Software & Licenses"),
                    ("tools", "Tools & Equipment"),
                    ("uniforms", "Uniforms & Clothing"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
