# Generated by Django 4.2.16 on 2026-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_stockitem_site_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="it_ip_address",
            field=models.CharField(
                blank=True, help_text="e.g. 192.168.1.100", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_license_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_mac_address",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_os",
            field=models.CharField(
                blank=True, help_text="e.g. Windows 11, Ubuntu 22.04", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_processor",
            field=models.CharField(
                blank=True, help_text="e.g. Intel Core i7-12700", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_ram_gb",
            field=models.CharField(
                blank=True, help_text="e.g. 16GB DDR4", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_storage",
            field=models.CharField(
                blank=True, help_text="e.g. 512GB SSD", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_supplier",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="asset",
            name="it_warranty_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
