# Generated by Django 4.2.16 on 2026-07-09 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolboxTalk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("date", models.DateField()),
                ("topic", models.CharField(max_length=300)),
                ("conducted_by", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("duration_minutes", models.PositiveIntegerField(default=15)),
                ("summary", models.TextField(blank=True, default="")),
                ("attendees", models.JSONField(default=list)),
                ("attendee_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toolbox_talks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteInduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("person_name", models.CharField(max_length=200)),
                ("company", models.CharField(blank=True, default="", max_length=200)),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                ("induction_date", models.DateField()),
                (
                    "inducted_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("topics_covered", models.TextField(blank=True, default="")),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_inductions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-induction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PPEIssuance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("person_name", models.CharField(max_length=200)),
                (
                    "employee_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "ppe_item",
                    models.CharField(
                        choices=[
                            ("helmet", "Safety Helmet"),
                            ("vest", "High-Vis Vest"),
                            ("boots", "Safety Boots"),
                            ("gloves", "Gloves"),
                            ("goggles", "Safety Goggles"),
                            ("earplugs", "Ear Plugs / Muffs"),
                            ("harness", "Safety Harness"),
                            ("respirator", "Respirator / Mask"),
                            ("coverall", "Coverall"),
                            ("other", "Other"),
                        ],
                        default="helmet",
                        max_length=20,
                    ),
                ),
                (
                    "ppe_description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("size", models.CharField(blank=True, default="", max_length=20)),
                ("issue_date", models.DateField()),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("good", "Good"), ("worn", "Worn")],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_issuances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HSEIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=300)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("near_miss", "Near Miss"),
                            ("first_aid", "First Aid"),
                            ("medical", "Medical Treatment"),
                            ("lost_time", "Lost Time Injury"),
                            ("fatality", "Fatality"),
                            ("property", "Property Damage"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        default="near_miss",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("persons_involved", models.TextField(blank=True, default="")),
                ("immediate_action", models.TextField(blank=True, default="")),
                ("root_cause", models.TextField(blank=True, default="")),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("corrective_action_due", models.DateField(blank=True, null=True)),
                (
                    "corrective_action_completed",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hse_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
