# Generated by Django 4.2.16 on 2026-07-09 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submittal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("submittal_number", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=255)),
                (
                    "submittal_type",
                    models.CharField(
                        choices=[
                            ("material_sample", "Material Sample"),
                            ("shop_drawing", "Shop Drawing"),
                            ("product_data", "Product Data"),
                            ("method_statement", "Method Statement"),
                            ("mix_design", "Mix Design"),
                            ("test_report", "Test Report"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        default="material_sample",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("submitted_by", models.CharField(blank=True, max_length=100)),
                ("reviewer", models.CharField(blank=True, max_length=100)),
                ("date_submitted", models.DateField(default=django.utils.timezone.now)),
                ("review_due", models.DateField(blank=True, null=True)),
                ("date_reviewed", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("approved_as_noted", "Approved as Noted"),
                            ("revise_resubmit", "Revise & Resubmit"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("review_comments", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=documents.models.submittal_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submittals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="RFI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("rfi_number", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("raised_by", models.CharField(blank=True, max_length=100)),
                ("directed_to", models.CharField(blank=True, max_length=100)),
                ("date_raised", models.DateField(default=django.utils.timezone.now)),
                ("response_due", models.DateField(blank=True, null=True)),
                ("response", models.TextField(blank=True)),
                ("responded_by", models.CharField(blank=True, max_length=100)),
                ("date_responded", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_raised"],
            },
        ),
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("drawing_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("civil", "Civil"),
                            ("structural", "Structural"),
                            ("architectural", "Architectural"),
                            ("mechanical", "Mechanical"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("survey", "Survey / GIS"),
                            ("geotechnical", "Geotechnical"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        default="civil",
                        max_length=30,
                    ),
                ),
                ("revision", models.CharField(default="A", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued_for_review", "Issued for Review"),
                            ("issued_for_construction", "Issued for Construction"),
                            ("as_built", "As Built"),
                            ("superseded", "Superseded"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("scale", models.CharField(blank=True, max_length=50)),
                ("drawn_by", models.CharField(blank=True, max_length=100)),
                ("checked_by", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=documents.models.drawing_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["drawing_number", "-revision"],
            },
        ),
    ]
