# Generated by Django 4.2.16 on 2026-07-09 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0010_employee_reports_to_work_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fleet", "0010_alter_keyissuance_return_body_condition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        help_text="Task / activity description",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("engineer", "Engineer"),
                            ("foreman", "Foreman"),
                            ("supervisor", "Supervisor"),
                            ("artisan", "Artisan"),
                            ("operator", "Operator"),
                            ("driver", "Driver"),
                            ("labourer", "Labourer"),
                            ("surveyor", "Surveyor"),
                            ("safety_officer", "Safety Officer"),
                            ("other", "Other"),
                        ],
                        default="labourer",
                        max_length=30,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("night", "Night"),
                            ("full", "Full Day"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("standby", "Standby"),
                            ("breakdown", "Breakdown"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="hr.employee",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labour_deployments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__last_name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentDeployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("excavator", "Excavator"),
                            ("grader", "Grader"),
                            ("roller", "Roller / Compactor"),
                            ("tipper", "Tipper Truck"),
                            ("concrete_mixer", "Concrete Mixer"),
                            ("crane", "Crane"),
                            ("bulldozer", "Bulldozer"),
                            ("water_bowser", "Water Bowser"),
                            ("generator", "Generator"),
                            ("vehicle", "Vehicle / Pickup"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "equipment_id_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reg no / asset tag if not in fleet",
                        max_length=100,
                    ),
                ),
                ("activity", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("night", "Night"),
                            ("full", "Full Day"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                ("operator_name", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("standby", "Standby"),
                            ("breakdown", "Breakdown"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("breakdown_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_deployments_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
