# Generated by Django 4.2.16 on 2026-06-27 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_asset_assetmaintenancelog"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceivedNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grn_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("received_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("confirmed", "Confirmed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="polineitem",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_line_items",
                to="inventory.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="GRNItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                            ("rejected", "Rejected"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grn_items",
                        to="procurement.goodsreceivednote",
                    ),
                ),
                (
                    "po_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grn_items",
                        to="procurement.polineitem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_received_notes",
                to="procurement.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceivednote",
            name="received_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_received_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
