# Generated by Django 4.2.16 on 2026-07-09 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_wbs_phase_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0002_goodsreceivednote_polineitem_stock_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rfq_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. civil materials, fuel, services",
                        max_length=100,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("closing_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued to Suppliers"),
                            ("evaluating", "Evaluating"),
                            ("awarded", "Awarded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="[{description, qty, unit}]"
                    ),
                ),
                ("award_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "awarded_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_rfqs",
                        to="procurement.supplier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs",
                        to="projects.project",
                    ),
                ),
                (
                    "suppliers",
                    models.ManyToManyField(
                        blank=True, related_name="rfqs", to="procurement.supplier"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PODeliverySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("milestone", models.CharField(max_length=255)),
                ("expected_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "quantity_expected",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "quantity_delivered",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("delivered", "Delivered"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedule",
                        to="procurement.purchaseorder",
                    ),
                ),
            ],
            options={
                "ordering": ["expected_date"],
            },
        ),
        migrations.CreateModel(
            name="RFQQuote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("validity_days", models.PositiveIntegerField(default=30)),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="[{description, qty, unit, unit_price, total}]",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("currency", models.CharField(default="KES", max_length=5)),
                ("delivery_days", models.PositiveIntegerField(blank=True, null=True)),
                ("payment_terms", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_recommended", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="procurement.rfq",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes_submitted",
                        to="procurement.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["total_amount"],
                "unique_together": {("rfq", "supplier")},
            },
        ),
    ]
