# Generated by Django 4.2.16 on 2026-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_site_operations_department"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_model_n_3fb686_idx",
            old_name="core_audit_model_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_user_id_2ff9b7_idx",
            old_name="core_audit_user_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
